import numpy as np

# SVG Dimensions and Layout
WIDTH = 100
HEIGHT = 100
PADDING = 10

# Points
GRID_COLOR = "white"
GRID_RAD = 0
CHORD_COLOR = "#333333"
CHORD_RAD = 2
TONIC_COLOR = "gray"
TONIC_RAD = 4
BASS_SIDELENGTH = CHORD_RAD * 2 + 2

# Lines
LINE_WIDTH = 2

# Grid spacing and layout
HORIZONTAL_DISTANCE = 20
VERTICAL_DISTANCE = 17
ROW_SHIFT = -14

N_COLS = 11
N_ROWS = 5